# -------------------------------------------------------------------
# If "apache_vhost_dir" is defined, the web root directories are
# extracted from the Apache2 virtual host configuration files. 
# Otherwise, web root directories are taken from the comma-separated 
# list of directory paths in "web_roots".
#
# Access to the Apache configuration files is usually prohibited on 
# commercial hosting services. The same applies to "run_as_root".
# -------------------------------------------------------------------
[website_reporter]
# Switch to False on commercial hosting services.
run_as_root = True
joomla_cli = php8.4 cli/joomla.php
mediawiki_cli = php8.4 maintenance/
wp_cli = wp
# comment out "apache_vhost_dir" to use "web_roots" instead
apache_vhost_dir = /etc/apache2/sites-enabled
web_roots = 
    /var/www/html,
    /var/www/joomla,
    /var/www/mediawiki,
    /var/www/wordpress